name: wasm-bindgen unit tests

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: jetli/wasm-pack-action@v0.4.0
    - name: Run tests
      run: wasm-pack test --chrome
